### ISSUE TITLE
deploy prevention-point/metabase

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevpoint-metabase#1]
Put this somewhere that is accessible to Prevention Point 

- not sure what this would require, but let's talk about it!

**Comment by mariekers** [comment]
## TODO

- [ ] Verify that application can be started locally with `docker-compose up`
- [ ] Fill out repository and branch below
- [ ] Set up CodeForPhilly.org project profile and add link below
- [ ] Record any additional notes, if any

## Deployment specifications

- **Repository:** https://github.com/CodeForPhilly/prevpoint-metabase
- **Branch:** master
- **Project Profile:** https://codeforphilly.org/projects/prevention_point_unified_reporting_system

## Additional notes
